using BaseForge.API.Extensions;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi;
using Scalar.AspNetCore;
using Marketplace.Data;

// h2c (TLS'siz HTTP/2) desteği — container/yerel ağda düz HTTP üzerinden gRPC istemci çağrıları için.
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);

var builder = WebApplication.CreateBuilder(args);

// Merkezi loglama: Serilog + (yapılandırılmışsa) Grafana Loki. Serilog:LokiUrl boşsa
// sadece konsola loglar — Loki'nin ayakta olması bir ön koşul değildir.
builder.AddBaseForgeLogging("marketplace");

// SPA'lardan (farklı origin) çağrılabilmesi için — izinli origin'ler appsettings/env'den
// gelir, kod değişikliği/regen gerekmez (bkz. appsettings.json "Cors:AllowedOrigins").
var allowedOrigins = builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>() ?? [];
builder.Services.AddCors(cors =>
{
    cors.AddPolicy("ConfiguredOrigins", policy =>
    {
        if (allowedOrigins.Length > 0)
        {
            policy.WithOrigins(allowedOrigins).AllowAnyHeader().AllowAnyMethod();
        }
    });
});

builder.Services.AddControllers();
builder.Services.AddGrpc(grpc => grpc.Interceptors.Add<BaseForge.API.Grpc.CorrelationIdServerInterceptor>());
builder.Services.AddOpenApi(openApi =>
{
    // Scalar'daki "Introduction" bölümü bu bilgilerden gelir (Markdown desteklenir).
    openApi.AddDocumentTransformer((document, _, _) =>
    {
        document.Info.Title = "Marketplace API";
        document.Info.Version = "v1";
        document.Info.Description = "# Marketplace API\n\nBaseForge ile üretilen **marketplace** mikroservisi · _marketplace microservice generated by BaseForge_.\n\n## 🇹🇷 Türkçe\nBu servis **marketplace** bounded context'ini yönetir ve şu kaynaklar için CRUD uçları sunar: **Category, Listing, Offer, Request, Favorite**. Her kaynak için oluşturma, güncelleme, silme (soft delete), tekil getirme ve listeleme uçları vardır.\n\nMimari: Clean Architecture + CQRS (MediatR). Veri erişimi: EF Core (+ karmaşık sorgular için Dapper). Veritabanı: PostgreSQL (servise özel, `hekimburada_marketplace_db`). Başka servislere referanslar yalnızca ID iledir (cross-DB FK yoktur).\n\n## 🇬🇧 English\nThe **marketplace** microservice owns the **marketplace** bounded context and exposes CRUD endpoints for: **Category, Listing, Offer, Request, Favorite**. Each resource provides create, update, delete (soft delete), get-by-id and list endpoints.\n\nArchitecture: Clean Architecture + CQRS (MediatR). Data access: EF Core (+ Dapper for complex queries). Database: PostgreSQL (per service, `hekimburada_marketplace_db`). References to other services are ID-only (no cross-DB foreign keys).";
        return Task.CompletedTask;
    });

    // JWT korumalı servis: OpenAPI dokümanına Bearer security scheme'i ekle
    // (Scalar'daki "Authentication" panelinin kaynağı budur).
    openApi.AddDocumentTransformer((document, _, _) =>
    {
        document.Components ??= new OpenApiComponents();
        document.Components.SecuritySchemes ??= new Dictionary<string, IOpenApiSecurityScheme>();
        document.Components.SecuritySchemes["Bearer"] = new OpenApiSecurityScheme
        {
            Type = SecuritySchemeType.Http,
            Scheme = "bearer",
            BearerFormat = "JWT",
            Description = "Identity'nin `/connect/token` ucundan aldığınız access_token'ı buraya yapıştırın.",
        };
        document.Security ??= [];
        document.Security.Add(new OpenApiSecurityRequirement
        {
            [new OpenApiSecuritySchemeReference("Bearer", document)] = [],
        });
        return Task.CompletedTask;
    });
});
builder.Services.AddBaseForge(options =>
{
    options.UsePostgreSQL<MarketplaceDbContext>(
        builder.Configuration.GetConnectionString("Default")
            ?? throw new InvalidOperationException("ConnectionStrings:Default tanımlı değil."));
    options.EnableCQRS(typeof(Program).Assembly);
    options.EnableAuditLog();
    options.EnableJwt(jwt =>
    {
        jwt.Authority = "http://host.docker.internal:5090";          // merkez Identity (discovery/JWKS)
        jwt.Audience = "hekimburada-api";
        jwt.RequireHttpsMetadata = false;
    });
});

// BaseForge gap (bkz. proje hafızası): CodeGen'in ürettiği AddInterceptor<CorrelationIdClientInterceptor>()
// çağrısı, interceptor'ı DI'a KENDİSİ kaydetmiyor — AddBaseForge de kaydetmiyor. Kayıt olmadan ilk
// gerçek gRPC çağrısında "No service for type ... has been registered" ile patlıyor (runtime'da bulundu).
builder.Services.AddTransient<BaseForge.API.Grpc.CorrelationIdClientInterceptor>();

// identity/User servisine gRPC istemcisi (BaseForge.CodeGen tarafından üretildi).
builder.Services.AddGrpcClient<Identity.Grpc.UserService.UserServiceClient>(o =>
    o.Address = new Uri(builder.Configuration["Grpc:Identity"]
        ?? throw new InvalidOperationException("Grpc:Identity tanımlı değil.")))
    .AddInterceptor<BaseForge.API.Grpc.CorrelationIdClientInterceptor>();
builder.Services.AddScoped<Marketplace.Integration.IUserClient, Marketplace.Integration.UserClient>();

// İlan yorumu bildirim e-postası için (bkz. Email/, Features/Notifications/).
var smtpOptions = builder.Configuration.GetSection(Marketplace.Email.SmtpOptions.SectionName).Get<Marketplace.Email.SmtpOptions>()
    ?? new Marketplace.Email.SmtpOptions();
builder.Services.AddSingleton(smtpOptions);
builder.Services.AddTransient<Marketplace.Email.IEmailSender, Marketplace.Email.SmtpEmailSender>();

// JWT issuer'ı elle sabitle — Authority/metadata-tabanlı otomatik keşif (BaseForge.EnableJwt'in
// varsayılanı) container restart sonrası ilk isteklerde bazen boş/eksik konfigürasyon
// döndürebiliyor ("IDX10204: ValidIssuer is null"), tüm istekleri 401'e düşürüyor — CodeGen dışı,
// prod olayı sonrası elle eklendi. "Auth:Issuer" tanımlıysa (prod'da Identity'nin kendi Issuer'ıyla
// aynı) metadata'ya bağımlılığı tamamen ortadan kaldırır; tanımlı değilse (yerel dev) eski davranış
// (Authority/metadata) korunur.
var jwtValidIssuer = builder.Configuration["Auth:Issuer"];
if (!string.IsNullOrWhiteSpace(jwtValidIssuer))
{
    builder.Services.Configure<JwtBearerOptions>(JwtBearerDefaults.AuthenticationScheme, options =>
    {
        options.TokenValidationParameters.ValidIssuer = jwtValidIssuer;
    });
}

var app = builder.Build();

// Reverse proxy (nginx vb.) arkasında çalışırken gerçek şema/host'u (https, gerçek domain)
// Kestrel'e bildirir — aksi halde OpenAPI/discovery gibi üretilen mutlak URL'ler yanlış (http,
// proxy'nin iç adresi) görünür. Docker port publish NAT'i yüzünden istek, proxy'nin gerçek IP'si
// yerine değişken bir docker gateway IP'sinden gelir; bu yüzden KnownNetworks/KnownProxies temizlenir
// (herkesten gelen X-Forwarded-* güvenilir sayılır). Güvenlik, container portunun yalnızca
// 127.0.0.1'e (host loopback) publish edilmesinden gelir — dışarıdan bu porta doğrudan erişilemez,
// yalnızca aynı host'taki nginx erişebilir.
var forwardedHeadersOptions = new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto,
};
forwardedHeadersOptions.KnownNetworks.Clear();
forwardedHeadersOptions.KnownProxies.Clear();
app.UseForwardedHeaders(forwardedHeadersOptions);

if (app.Environment.IsDevelopment())
{
    // Hızlı başlangıç: migration yerine şemayı oluştur (yalnızca geliştirme).
    // Postgres erişilemezse uygulama yine de açılır; API arayüzü görülebilir.
    try
    {
        using var scope = app.Services.CreateScope();
        scope.ServiceProvider.GetRequiredService<MarketplaceDbContext>().Database.EnsureCreated();
    }
    catch (Exception ex)
    {
        app.Logger.LogWarning(ex, "Veritabanı şeması oluşturulamadı (Postgres çalışıyor mu?). API arayüzü yine de açık.");
    }

    // API arayüzü: /scalar/v1 (OpenAPI: /openapi/v1.json)
    app.MapOpenApi();
    app.MapScalarApiReference(options =>
    {
        options.WithTitle("Marketplace API");
        options.WithTheme(ScalarTheme.Default);
        // Dark mode toggle varsayılan açık. Gizlemek için: options.HideDarkModeToggle();

        // "Ask AI" (Agent Scalar): localhost'ta key'siz ücretsiz/limitli çalışır.
        // Production'da Scalar Agent key'i ver: options.WithAgentKey("SCALAR_AGENT_KEY");
        // Veya veri gizliliği için tamamen kapat:        options.DisableAgent();

        // Token'ı Identity'nin /connect/token ucundan alıp buraya bir kere yapıştırın;
        // "Persist" sayesinde sayfa yenilense de kaybolmaz (localStorage).
        options.AddHttpAuthentication("Bearer", auth => auth.WithToken(string.Empty));
        options.AddPreferredSecuritySchemes("Bearer");
        options.EnablePersistentAuthentication();
    });
}

app.UseCors("ConfiguredOrigins");
app.UseStaticFiles(); // wwwroot/uploads — MediaController'ın fiziksel olarak kaydettiği dosyalar için
app.UseBaseForge();
app.MapControllers();
app.MapGrpcService<Marketplace.Grpc.CategoryGrpcService>();
app.MapGrpcService<Marketplace.Grpc.ListingGrpcService>();
app.MapGrpcService<Marketplace.Grpc.OfferGrpcService>();
app.MapGrpcService<Marketplace.Grpc.RequestGrpcService>();
app.MapGrpcService<Marketplace.Grpc.FavoriteGrpcService>();
app.Run();
