using BaseForge.API.Extensions;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi;
using Scalar.AspNetCore;
using Gateway.Data;

// h2c (TLS'siz HTTP/2) desteği — container/yerel ağda düz HTTP üzerinden gRPC istemci çağrıları için.
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);

var builder = WebApplication.CreateBuilder(args);

// Merkezi loglama: Serilog + (yapılandırılmışsa) Grafana Loki. Serilog:LokiUrl boşsa
// sadece konsola loglar — Loki'nin ayakta olması bir ön koşul değildir.
builder.AddBaseForgeLogging("gateway");

// SPA'lardan (farklı origin) çağrılabilmesi için — izinli origin'ler appsettings/env'den
// gelir, kod değişikliği/regen gerekmez (bkz. appsettings.json "Cors:AllowedOrigins").
var allowedOrigins = builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>() ?? [];
builder.Services.AddCors(cors =>
{
    cors.AddPolicy("ConfiguredOrigins", policy =>
    {
        if (allowedOrigins.Length > 0)
        {
            policy.WithOrigins(allowedOrigins).AllowAnyHeader().AllowAnyMethod();
        }
    });
});

builder.Services.AddControllers();
builder.Services.AddGrpc(grpc => grpc.Interceptors.Add<BaseForge.API.Grpc.CorrelationIdServerInterceptor>());
builder.Services.AddOpenApi(openApi =>
{
    // Scalar'daki "Introduction" bölümü bu bilgilerden gelir (Markdown desteklenir).
    openApi.AddDocumentTransformer((document, _, _) =>
    {
        document.Info.Title = "Gateway API";
        document.Info.Version = "v1";
        document.Info.Description = "# Gateway API\n\nBaseForge ile üretilen **gateway** mikroservisi · _gateway microservice generated by BaseForge_.\n\n## 🇹🇷 Türkçe\nBu servis **gateway** bounded context'ini yönetir ve şu kaynaklar için CRUD uçları sunar: **Announcement**. Her kaynak için oluşturma, güncelleme, silme (soft delete), tekil getirme ve listeleme uçları vardır.\n\nMimari: Clean Architecture + CQRS (MediatR). Veri erişimi: EF Core (+ karmaşık sorgular için Dapper). Veritabanı: PostgreSQL (servise özel, `hekimburada_gateway_db`). Başka servislere referanslar yalnızca ID iledir (cross-DB FK yoktur).\n\n## 🇬🇧 English\nThe **gateway** microservice owns the **gateway** bounded context and exposes CRUD endpoints for: **Announcement**. Each resource provides create, update, delete (soft delete), get-by-id and list endpoints.\n\nArchitecture: Clean Architecture + CQRS (MediatR). Data access: EF Core (+ Dapper for complex queries). Database: PostgreSQL (per service, `hekimburada_gateway_db`). References to other services are ID-only (no cross-DB foreign keys).";
        return Task.CompletedTask;
    });

    // JWT korumalı servis: OpenAPI dokümanına Bearer security scheme'i ekle
    // (Scalar'daki "Authentication" panelinin kaynağı budur).
    openApi.AddDocumentTransformer((document, _, _) =>
    {
        document.Components ??= new OpenApiComponents();
        document.Components.SecuritySchemes ??= new Dictionary<string, IOpenApiSecurityScheme>();
        document.Components.SecuritySchemes["Bearer"] = new OpenApiSecurityScheme
        {
            Type = SecuritySchemeType.Http,
            Scheme = "bearer",
            BearerFormat = "JWT",
            Description = "Identity'nin `/connect/token` ucundan aldığınız access_token'ı buraya yapıştırın.",
        };
        document.Security ??= [];
        document.Security.Add(new OpenApiSecurityRequirement
        {
            [new OpenApiSecuritySchemeReference("Bearer", document)] = [],
        });
        return Task.CompletedTask;
    });
});
builder.Services.AddBaseForge(options =>
{
    options.UsePostgreSQL<GatewayDbContext>(
        builder.Configuration.GetConnectionString("Default")
            ?? throw new InvalidOperationException("ConnectionStrings:Default tanımlı değil."));
    options.EnableCQRS(typeof(Program).Assembly);
    options.EnableAuditLog();
    options.EnableJwt(jwt =>
    {
        jwt.Authority = builder.Configuration["Auth:Authority"] ?? "http://host.docker.internal:5090"; // merkez Identity (discovery/JWKS)
        jwt.Audience = "hekimburada-api";
        jwt.RequireHttpsMetadata = false;
    });
});

// BaseForge gap (bkz. proje hafızası): CodeGen'in ürettiği AddInterceptor<CorrelationIdClientInterceptor>()
// çağrısı, interceptor'ı DI'a KENDİSİ kaydetmiyor — AddBaseForge de kaydetmiyor. Kayıt olmadan ilk
// gerçek gRPC çağrısında "No service for type ... has been registered" ile patlıyor (runtime'da bulundu).
builder.Services.AddTransient<BaseForge.API.Grpc.CorrelationIdClientInterceptor>();

// identity/User servisine gRPC istemcisi (BaseForge.CodeGen tarafından üretildi).
builder.Services.AddGrpcClient<Identity.Grpc.UserService.UserServiceClient>(o =>
    o.Address = new Uri(builder.Configuration["Grpc:Identity"]
        ?? throw new InvalidOperationException("Grpc:Identity tanımlı değil.")))
    .AddInterceptor<BaseForge.API.Grpc.CorrelationIdClientInterceptor>();
builder.Services.AddScoped<Gateway.Integration.IUserClient, Gateway.Integration.UserClient>();

// Gateway: kardeş servislerin TÜM /api/* yüzeyini /api/gateway/{servis}/... altında şeffafça
// ileten YARP reverse-proxy — route/cluster tanımları appsettings.json "ReverseProxy" bölümünden
// gelir (bkz. docs/ARCH.md §5.8). [Authorize] bu uçlara UYGULANMAZ (MapReverseProxy MVC pipeline
// dışında çalışır) — gerçek yetkilendirme sınırı hâlâ Authorization header'ının şeffafça iletildiği
// hedef serviste.
builder.Services.AddReverseProxy().LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"));

var app = builder.Build();

// Reverse proxy (nginx vb.) arkasında çalışırken gerçek şema/host'u (https, gerçek domain)
// Kestrel'e bildirir — aksi halde OpenAPI/discovery gibi üretilen mutlak URL'ler yanlış (http,
// proxy'nin iç adresi) görünür. Docker port publish NAT'i yüzünden istek, proxy'nin gerçek IP'si
// yerine değişken bir docker gateway IP'sinden gelir; bu yüzden KnownNetworks/KnownProxies temizlenir
// (herkesten gelen X-Forwarded-* güvenilir sayılır). Güvenlik, container portunun yalnızca
// 127.0.0.1'e (host loopback) publish edilmesinden gelir — dışarıdan bu porta doğrudan erişilemez,
// yalnızca aynı host'taki nginx erişebilir.
var forwardedHeadersOptions = new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto,
};
forwardedHeadersOptions.KnownNetworks.Clear();
forwardedHeadersOptions.KnownProxies.Clear();
app.UseForwardedHeaders(forwardedHeadersOptions);

// Hızlı başlangıç: migration yerine şemayı oluştur (repo'da EF Core migration yok, prod dahil her ortamda bu yol kullanılıyor).
try
{
    using var scope = app.Services.CreateScope();
    scope.ServiceProvider.GetRequiredService<GatewayDbContext>().Database.EnsureCreated();
}
catch (Exception ex)
{
    app.Logger.LogWarning(ex, "Veritabanı şeması oluşturulamadı (Postgres çalışıyor mu?). API arayüzü yine de açık.");
}

if (app.Environment.IsDevelopment())
{
    // API arayüzü: /scalar/v1 (OpenAPI: /openapi/v1.json)
    app.MapOpenApi();
    app.MapScalarApiReference(options =>
    {
        options.WithTitle("Gateway API");
        options.WithTheme(ScalarTheme.Default);
        // Dark mode toggle varsayılan açık. Gizlemek için: options.HideDarkModeToggle();

        // "Ask AI" (Agent Scalar): localhost'ta key'siz ücretsiz/limitli çalışır.
        // Production'da Scalar Agent key'i ver: options.WithAgentKey("SCALAR_AGENT_KEY");
        // Veya veri gizliliği için tamamen kapat:        options.DisableAgent();

        // Token'ı Identity'nin /connect/token ucundan alıp buraya bir kere yapıştırın;
        // "Persist" sayesinde sayfa yenilense de kaybolmaz (localStorage).
        options.AddHttpAuthentication("Bearer", auth => auth.WithToken(string.Empty));
        options.AddPreferredSecuritySchemes("Bearer");
        options.EnablePersistentAuthentication();
    });
}

app.UseCors("ConfiguredOrigins");
app.UseStaticFiles(); // wwwroot/uploads — MediaController'ın fiziksel olarak kaydettiği dosyalar için
app.UseBaseForge();
app.MapControllers();
app.MapReverseProxy();
app.MapGrpcService<Gateway.Grpc.AnnouncementGrpcService>();
app.Run();
